from . import kinesiology_cash_movement
from . import kinesiology_diagnoses
from . import kinesiology_health_insurance
from . import kinesiology_institutions
from . import kinesiology_localities
from . import kinesiology_medical_offices
from . import kinesiology_patients
from . import kinesiology_professionals
from . import kinesiology_records
from . import kinesiology_treatments
from . import kinesiology_turns